### PR TITLE
support 2024.5.1

### PR DESCRIPTION
**Pull request by sr01**
- fix calls from callback thread to main thread
- replace deprecated enums & constants

### CODE REVIEW

**Comment by leranp** [comment]
the owner of this repo doesnt have this product any more.
i can say that this PR is fixing the problem after the 2024.5.1 version.

**Review by leranp — APPROVED** [review]

**Comment by hllhll** [comment]
awesome , thank you both I'll merge it when I have some spare time

**Comment by eyalpost** [comment]
Copy pasted this into `climate.py` and things are back to normal 🙂 
Thanks!

**Comment by hllhll** [comment]
according to comments, this works, thanks for the pr @sr01

**Comment by RoiS8** [comment]
Same here, all seem to work fine now.
Thank you @sr01 & @hllhll

**Pull request merged**
